### ISSUE TITLE
Make master a protected branch

### ISSUE THREAD

**Issue by Byvire** [Agizin/Algorithm-Visualization#2]
See here: https://help.github.com/articles/configuring-protected-branches/
The owner of the repo (Jonathan) needs to do this.
Once we do this, we won't be able to merge to master until somebody reviews and approves a pull request.

**Comment by Agizin** [comment]
Master should be protected now. I also enabled a separate option to require reviews for pull requests. Let me know if there is anything else that needs changing.

**Comment by Byvire** [comment]
Awesome.  I can't merge now.
