### ISSUE TITLE
Defining general shape drawings

### ISSUE THREAD

**Issue by Agizin** [Agizin/Algorithm-Visualization#7]
On the visualizer-general branch I started writing a class to define general behavior for all data structure visualizers. In particular, this class will define the default interactions with svgwrite so that we can have a consistent design. Already, I've added support for generic circles, lines, rectangles, rounded rectangles, ellipses, and text. 

At the very least, I've identified that we need to add support for all other regular polygons, arrows and a consistent way to write text to a shape/line.

Are there any other shapes or svg features that we should define here? Is there anything that we should define here unrelated to drawing shapes that needs to be consistent across all data structure visualizers?

**Comment by Byvire** [comment]
What does "support for regular polygons" look like?  Is is something like the following (maybe as a method)?
```python
draw_regular_polygon(n=5, point_up=True, radius=40, contents=None)
```
Does an arrow have start and end elements (e.g. a certain circle to a certain pentagon?) or start and end points (e.g. (0, 5) to (110, 180))?

**Comment by Byvire** [comment]
It would be very nice if way arrows connected to data structures were standardized, e.g. by making an API to handle connecting arrows to components of our pictures.
But maybe that should happen at a higher layer of abstraction?
I guess here's a related question:   Who (which component of our project) will use the API you describe in this issue?
