### ISSUE TITLE
Toy tool to make pictures of graphs

### ISSUE THREAD

**Issue by Byvire** [Agizin/Algorithm-Visualization#8]
Please implement a tool to parse JSON descriptions of graphs (using the `parsers.json_objects` module) and produce pictures of graphs directly with pygraphviz.
It's about time we had some fun.

**Comment by Byvire** [comment]
Done.  I could make a pull request, but it depends on another PR that hasn't been merged yet.

**Comment by Byvire** [comment]
@Agizin Will you please review my pull request, #9 ?  It has been sitting in limbo for over a week now.

**Comment by Agizin** [comment]
I can if necessary but I have less free time than expected this week - I wouldn't be able to get to it until the weekend at least. @Palikadude might be a better reviewer - I believe he looked into pygraphviz already and we should get more team members involved in the code review process.
